# -*- coding: utf-8 -*-
"""24 个新增维度的定义：key / 中英文名 / 匹配关键词 / 维度边界说明。"""
NEW_DIMS3 = [
    {"key": "ttl", "zh": "TTL 与数据生命周期管理", "en": "TTL & data lifecycle",
     "keys": ["TTL", "ttl", "生命周期", "Lifecycle", "数据过期"],
     "scope": "行级/分区级自动过期删除、冷热分层、归档策略。不含备份保留（那是备份恢复维度）。"},
    {"key": "online_ddl", "zh": "在线 DDL 与 Schema 演进", "en": "Online DDL & schema evolution",
     "keys": ["在线 DDL", "Online DDL", "Schema 演进", "schema evolution"],
     "scope": "加列/改列/建索引是否锁表、在线变更机制、大表 DDL 风险与工具（gh-ost/pt-osc）。"},
    {"key": "multitenant", "zh": "多租户与资源隔离", "en": "Multi-tenancy & resource isolation",
     "keys": ["多租户", "资源隔离", "Multi-tenancy", "multi-tenancy", "资源组"],
     "scope": "同一集群内多业务/租户的 CPU/内存/IO 限流与 QoS。不含认证隔离（那是认证与权限维度）。"},
    {"key": "multi_region", "zh": "跨地域多活", "en": "Cross-region active-active",
     "keys": ["多活", "跨地域", "active-active", "Active-active", "multi-region"],
     "scope": "多 region 写入、就近读、region 级容灾。与“支持跨云”（多云厂商）区分：这里指地理多活。"},
    {"key": "ha_rto", "zh": "高可用架构与 RTO/RPO", "en": "HA & RTO/RPO",
     "keys": ["高可用", "RTO", "RPO", "故障切换", "failover", "High availability"],
     "scope": "自动故障切换、脑裂防护、RTO/RPO 量级。偏可用性目标，不重复复制机制细节。"},
    {"key": "rls_mask", "zh": "行级安全与数据脱敏", "en": "Row-level security & masking",
     "keys": ["行级安全", "数据脱敏", "脱敏", "RLS", "masking"],
     "scope": "RLS、列级权限、动态脱敏。不含认证登录与审计日志。"},
    {"key": "json_semi", "zh": "JSON 与半结构化能力", "en": "JSON & semi-structured",
     "keys": ["半结构化", "semi-structured", "JSONB", "jsonb"],
     "scope": "JSON 类型、索引（GIN 等）、查询算子深度。"},
    {"key": "fulltext", "zh": "全文检索能力", "en": "Full-text search",
     "keys": ["全文检索", "全文索引", "Full-text", "full-text", "全文搜索"],
     "scope": "自带全文索引/分词 vs 必须外挂 ES。中文分词支持情况。"},
    {"key": "storage_eff", "zh": "存储效率与压缩", "en": "Storage efficiency & compression",
     "keys": ["存储效率", "存储放大", "Compression", "数据压缩"],
     "scope": "压缩算法与压缩比、存储放大/写放大。不含备份压缩。"},
    {"key": "license_risk", "zh": "开源协议与厂商锁定风险", "en": "OSS license & lock-in risk",
     "keys": ["厂商锁定", "lock-in", "Lock-in", "SSPL", "开源协议"],
     "scope": "协议变更史（SSPL/Elastic License）、fork 生态、迁移出成本。不含价格。"},
    {"key": "optimizer", "zh": "查询优化器与计划稳定性", "en": "Optimizer & plan stability",
     "keys": ["查询优化器", "计划稳定性", "执行计划", "plan stability"],
     "scope": "CBO 完备度、hint、计划绑定/冻结、执行计划翻转风险。"},
    {"key": "tuning", "zh": "参数调优与自治能力", "en": "Tuning & autonomy",
     "keys": ["参数调优", "自治", "autonomous", "Autonomous", "调优复杂度"],
     "scope": "参数数量级、autotune、AWR/ASH 类诊断。不含可观测性大盘。"},
    {"key": "corruption", "zh": "静默数据损坏防护", "en": "Silent corruption protection",
     "keys": ["静默损坏", "corruption", "Corruption", "checksum", "页校验"],
     "scope": "页 checksum、损坏检测、自愈。不含备份恢复流程。"},
    {"key": "sp_proc", "zh": "存储过程/触发器/过程语言", "en": "Stored procedures & triggers",
     "keys": ["存储过程", "触发器", "过程语言", "Stored procedure"],
     "scope": "过程语言完备度、调试工具、去 O 迁移时的改写成本。"},
    {"key": "constraints", "zh": "约束与数据完整性", "en": "Constraints & integrity",
     "keys": ["数据完整性", "完整性约束", "外键约束", "integrity"],
     "scope": "外键、CHECK、唯一约束、deferred；分布式库的限制。"},
    {"key": "analytical_sql", "zh": "分析 SQL 完备性", "en": "Analytical SQL",
     "keys": ["分析 SQL", "窗口函数", "window function", "分析函数"],
     "scope": "窗口函数、CTE、递归、GROUPING SETS 等。不含物化视图。"},
    {"key": "erasure", "zh": "被遗忘权与数据擦除", "en": "Right to erasure",
     "keys": ["被遗忘", "数据擦除", "erasure", "Erasure", "删除权"],
     "scope": "GDPR 删除权的工程实现：hard delete、LSM 墓碑、擦除证明。不含拿证。"},
    {"key": "lineage", "zh": "数据血缘与目录集成", "en": "Data lineage & catalog",
     "keys": ["数据血缘", "血缘", "lineage", "Lineage", "数据目录"],
     "scope": "OpenLineage/DataHub/Atlan 对接、数据发现。不含审计日志。"},
    {"key": "storage_compute", "zh": "存算分离 vs 存算一体", "en": "Storage-compute architecture",
     "keys": ["存算分离", "存算一体", "存算", "disaggregated"],
     "scope": "架构范式：共享存储 vs 本地盘，对弹性/成本/故障域的影响。不含扩展操作。"},
    {"key": "multi_model", "zh": "多模能力", "en": "Multi-model",
     "keys": ["多模", "Multi-model", "multi-model", "多模型"],
     "scope": "一库多用：文档+向量+全文+图。不含时序/图专库。"},
    {"key": "finops", "zh": "FinOps 成本可观测性", "en": "FinOps & cost observability",
     "keys": ["FinOps", "finops", "成本可观测", "成本归因"],
     "scope": "计费粒度、成本归因标签、预算告警。不含价格数字。"},
    {"key": "drivers", "zh": "驱动与多语言生态", "en": "Drivers & clients",
     "keys": ["驱动", "Driver", "JDBC", "ODBC", "客户端生态"],
     "scope": "各语言驱动质量、JDBC/ODBC、ORM 兼容。偏开发接入。"},
    {"key": "matview", "zh": "物化视图", "en": "Materialized views",
     "keys": ["物化视图", "Materialized view", "materialized view", "预聚合"],
     "scope": "物化视图类型、增量刷新、查询自动改写。不含分析 SQL 函数。"},
    {"key": "multi_cloud", "zh": "支持跨云", "en": "Multi-cloud support",
     "keys": ["跨云", "多云", "Multi-cloud", "multi-cloud"],
     "scope": "同一产品横跨 AWS/Azure/GCP/阿里云/腾讯云的可部署性、跨云复制。与跨地域多活区分：这里指多云厂商。"},
]

SLUGS = ["alloydb", "aurora", "cassandra-scylladb", "clickhouse", "cockroachdb",
         "databricks", "doris", "duckdb", "dynamodb", "edb", "etcd", "mariadb",
         "milvus", "mongodb", "mysql", "oceanbase", "oracle", "polardb",
         "postgresql", "qdrant", "redis-valkey", "snowflake", "spanner",
         "sqlserver", "starrocks", "tdsql", "tidb", "weaviate", "yugabytedb",
         "redshift", "bigquery"]
